### ISSUE TITLE
[Bug and Question] Merge elements of two ".mkv" into one ".mkv" on windows with network folders.

### ISSUE THREAD

**Issue by zFerry98** [akai10tsuki/mkvbatchmultiplex#2]
I don't understand, both V1 and V2 don't say why. Basically I have to batch a 64 episode series, I have to change the original video track with the hevc version and delay it for 1000ms. I do all the necessary things and copy the command from the shell. I paste the command and do analyze, it says OK (Structure looks OK :).
![image](https://user-images.githubusercontent.com/17975351/85953197-e94e8600-b96e-11ea-9c05-785d7838f6d6.png)
I click on process and says ok for all 64 in type 20 total seconds. No new files are created and nothing happens.

`C:\Users\MSI\Downloads\EXE\mkvtoolnix\mkvmerge.exe --ui-language it --output ^"Y:\Anime2\Fullmetal Alchemist Brotherhood\Stagione 01\Fullmetal Alchemist Brotherhood - s01e64 - stress - La fine del viaggio1.mkv^" --audio-tracks 1 --no-video --subtitle-tracks 3 --no-chapters --language 1:ita --track-name ^"1:Italiano AC3 5.1^" --default-track 1:yes --language 3:ita --track-name 3:Cartelli --default-track 3:yes ^"^(^" ^"Y:\Anime2\Fullmetal Alchemist Brotherhood\Stagione 01\Fullmetal Alchemist Brotherhood - s01e63 - stress - L'altro lato del cancello.mkv^" ^"^)^" --language 0:jpn --display-dimensions 0:1916x1076 --language 1:jpn --track-name ^"1:Giapponese AC3 2.0^" --language 2:ita --track-name 2:Dialoghi --language 3:eng --track-name 3:Dialoghi ^"^(^" ^"Y:\Anime2\Fullmetal Alchemist Brotherhood\Stagione 01\Fullmetal Alchemist Brotherhood - s01e64 - stress - La fine del viaggio.mkv^" ^"^)^" --track-order 1:0,0:1,1:1,0:3,1:2,1:3`

Found the problem but I don't know why it happens: `C:\Users\MSI\Downloads\EXE\mkvtoolnix\mkvmerge.exe`
if put as shell, when you do output command (the one to see what it would do) it doesn't put "  \  " in the path (only for the path of mkvtoolnix). Fix: "" at the beginning and end. It happens with both V1 and V2.

**Comment by akai10tsuki** [comment]
Hi,

The program generates a log it would be helpful.   Also a list of the directories of the source files to see if it is a naming issue in the operating system.

I will test the program using network directories as soon as I can.  I never done this before.

**Comment by zFerry98** [comment]
Windows 10 pro Italian + Non unicode Japanese.
In this case I have already done the batch. The problem was the absence of "" at the beginning and end of the Mkvtoolnix path.

**Comment by akai10tsuki** [comment]
Problem was replicated using portable mkvtoolnix tools.

In Windows the standard installation for mkvmerge 64 bit is  C:\Program Files\MKVToolNix\mkvmerge.exe the space in the name
forces escaped for the shell thus:

Command: ['C:\\Program Files\\MKVToolNix\\mkvmerge.exe', ...

The command is escaped correctly for the OS resulting in \\ for \ (double backslash for the single backslash.)

When running in Windows there and there is no space in the mkvmerge executable path '\' (backslash character) is use as escape and since is only one the path turns invalid.

The command is left as is which works for the real command shell but not for the sub process use in the program.

Command: ['C:binmkvtoolnixmkvmerge.exe', ...

Solution:
   Force escape quotes for mkvmerge executable in Windows

   The command is escaped for the command shell resulting in \\ for \:

   Command: ['C:\\bin\\mkvtoolnix\\mkvmerge.exe'

Patched executable:

https://github.com/akai10tsuki/mkvbatchmultiplex/releases/download/v2.0.0a1/MKVBatchMultiplex-iss-AMD64-2.0.0a2dev2.exe

Please test with executable until the official patched executable is released.

**Comment by zFerry98** [comment]
👌
