### ISSUE TITLE
[BUG] Error source files total mismatched

### ISSUE THREAD

**Issue by zFerry98** [akai10tsuki/mkvbatchmultiplex#3]
Almost 90% of the times I enter the command I get this error:

` Command looks ok.
Command looks ok.
Analysis of command line:
chk: Command seems ok.
chk: mkvmerge ok - C:\Users\MSI\Downloads\EXE\mkvtoolnix\mkvmerge.exe.
chk: Destination directory ok = Y:\Anime2\Boruto - Naruto Next Generations\Episodes 001-016 (The Ghost Incident).
chk: Source directory ok - Y:\Anime2\Boruto - Naruto Next Generations\Episodes 001-016 (The Ghost Incident).
chk: Source directory ok - Z:\Anime Backups\Boruto\Erai-raws\Italian_1-77.
err: Error source files total mismatched.--language 0:ita --track-name '0:Crunchyroll Ita' --default-track 0:yes --sync 0:26 '(' 'Z:\Anime Backups\Boruto\Erai-raws\Italian_1-77\[Erai-raws] Boruto - Naruto Next Generations - 01 [720p][Multiple Subtitle]_track8_ita.ass' ')'`

### The command is this:

`C:\Users\MSI\Downloads\EXE\mkvtoolnix\mkvmerge.exe --ui-language it --output ^"Y:\Anime2\Boruto - Naruto Next Generations\Episodes 001-016 ^(The Ghost Incident^)\Boruto - s01e01 - AnimeRG - Uzumaki Boruto^!^! ^(1^).mkv^" --language 0:jpn --track-name ^"0:[AnimeRG]^" --default-track 0:yes --display-dimensions 0:1920x1080 --language 1:jpn --track-name ^"1:Japanese Stereo^" --default-track 1:yes --sub-charset 2:UTF-8 --language 2:eng --track-name ^"2:Crunchyroll Eng^" --sub-charset 3:UTF-8 --language 3:ita --track-name ^"3:Crunchyroll Ita SRT^" ^"^(^" ^"Y:\Anime2\Boruto - Naruto Next Generations\Episodes 001-016 ^(The Ghost Incident^)\Boruto - s01e01 - AnimeRG - Uzumaki Boruto^!^!.mkv^" ^"^)^" --language 0:ita --track-name ^"0:Crunchyroll Ita^" --default-track 0:yes --sync 0:26 ^"^(^" ^"Z:\Anime Backups\Boruto\Erai-raws\Italian_1-77\[Erai-raws] Boruto - Naruto Next Generations - 01 [720p][Multiple Subtitle]_track8_ita.ass^" ^"^)^" --track-order 0:0,0:1,0:2,0:3,1:0`

Almost everything I try to automate with this tool gives me this error.

![image](https://user-images.githubusercontent.com/17975351/89119823-72e2fd80-d4b1-11ea-93ac-a296d010d1ff.png)
![image](https://user-images.githubusercontent.com/17975351/89119825-78d8de80-d4b1-11ea-8f38-38fac9ea4ffc.png)

**Comment by moralia** [comment]
Same for me. Problems with subs. With audio no problem, but with subs .ass or .srt problems. Hlep?

**Comment by akai10tsuki** [comment]
The premise for the program is to apply the same instruction to all the files in the batch.  That is if I am working to two sub files to the first episode there has to be 2 sub file for every episode for this example to work the files has to be organised in sub directories

Sub 1
F:\Sub1\SubA1.srt
F:\Sub1\SubA2.srt

Sub 2
F:\Sub2\SubB1.srt
F:\Sub2\SubB2.srt

Video
F:\Video\Video 1.mkv
F:\Video\Video 2.mkv

Here the program will match Video 1.mkv + SubA1;.srt + SubA2.srt  and Video 2.mkv + SubA2.srt + SubA3.srt

If everything is in one sub sub directory it will count 2 video sources and 4 subs sources and there is the mismatch.

This is the more common example for this message to trigger.

The program should be generating a log.  If the log can be posted I may get a more specific idea of the problem.

I need a description of the sources layout to find and resolve the issue.

PS:  The program don't read file names I found that it defeated the batch process to much.  The order of the files is what is taken into account.  That is the reason that it will work best if every source has it's own directory.  It's also easier to detect any problems.

**Comment by akai10tsuki** [comment]
Hi,

Added more info to track the source files origin.

https://github.com/akai10tsuki/mkvbatchmultiplex/releases/download/v2.0.0a1/MKVBatchMultiplex-iss-AMD64-2.0.0a2dev1.exe

version 2.0.0a2dev1

Check Files will display the destination and sources it finds.  The total number of files in each directory must match.  If they don't
commands will not be generated.

This has nothing to do with a sound command line. That is the meaning of looks good. To test everything is a very costly transaction so the GUI will freeze if we are looking to a sizable series. And again this is a batch process so no user input should be expected at execution time.  And all files must be equal in structure for the same reason.  This is not the case for many downloaded series and for v3.0 I started to look for ways to relax the strict **"equal in structure"**.

Ej.

Video 1 has:
 1 video track
 2 audio track
 3 subtitle track eng
 4 subtitle track esp

Video 1 has:
 1 video track
 2 audio track
 3 subtitle track esp
 4 subtitle track eng

The structure is not equal because the order of the subs eng and esp for video 1 and esp and eng for sub for video 2.

I work on video rips made by me so they are more or less done the same way and don't have this configurations to work with and my collection has 1500+ series accumulated over years.

To tackle situations like the one presented here I have to make  modifications that have to identify track order and alter that order which until now did not have to.

I will freeze version 2.0.0 and give priority to work with cases like these and groups like Erai-raws with so many subs out of order and missing in some episodes that has been presented to me by friends and until now I always say wait.

**Comment by zFerry98** [comment]
So. Normally the use is:
**1)** Series downloaded from the web with + audio and subs = remove from the same file X audio tracks and X subs (+ change of name to subs and tracks in general ... eg: ASS eng [Doki Fansub]> [Full] Doki Fansub ) This thing applied for the remaining ep in the same folder.

**2)** Series downloaded from the web with usual unnecessary audio and subs and addition (from another folder) of Subs and audio that I need. Eg a fansub makes better subs for that series than the official ones.

----------------------------------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/17975351/89391718-db77e780-d708-11ea-90ba-dd3393f09555.png)
As you can see they are the mkv in a network folder different from that of the Subs.

**Original MKV Struck:** 
![image](https://user-images.githubusercontent.com/17975351/89392134-6953d280-d709-11ea-8b25-3884e1b7d58e.png)

**Edited + Subs from another network folder:** 
![image](https://user-images.githubusercontent.com/17975351/89392201-838db080-d709-11ea-98a1-72e98db09bb7.png)

`C:\Users\MSI\Downloads\EXE\mkvtoolnix\mkvmerge.exe --ui-language it --output ^"Y:\Anime2\Boruto - Naruto Next Generations\Episodes 001-016 ^(The Ghost Incident^)\Boruto - s01e01 - AnimeRG - Uzumaki Boruto^!^! ^(1^).mkv^" --language 0:jpn --track-name ^"0:[AnimeRG]^" --default-track 0:yes --display-dimensions 0:1920x1080 --language 1:jpn --track-name ^"1:Japanese Stereo^" --default-track 1:yes --sub-charset 2:UTF-8 --language 2:eng --track-name ^"2:Crunchyroll Eng^" --sub-charset 3:UTF-8 --language 3:ita --track-name ^"3:Crunchyroll Ita SRT^" ^"^(^" ^"Y:\Anime2\Boruto - Naruto Next Generations\Episodes 001-016 ^(The Ghost Incident^)\Boruto - s01e01 - AnimeRG - Uzumaki Boruto^!^!.mkv^" ^"^)^" --language 0:ita --track-name ^"0:Crunchyroll Ita^" --default-track 0:yes --sync 0:26 ^"^(^" ^"Z:\Anime Backups\Boruto\Erai-raws\Italian_1-77\[Erai-raws] Boruto - Naruto Next Generations - 01 [720p][Multiple Subtitle]_track8_ita.ass^" ^"^)^" --track-order 0:0,0:1,0:2,1:0,0:3` Copied

### Result: 
![image](https://user-images.githubusercontent.com/17975351/89392484-e0896680-d709-11ea-92e1-93bb76da634f.png)

### Dirs:

**1)** 
![image](https://user-images.githubusercontent.com/17975351/89392620-13cbf580-d70a-11ea-9993-927ce369ef40.png) MKV

**2)**
![image](https://user-images.githubusercontent.com/17975351/89392714-30682d80-d70a-11ea-970f-60bf5eec5340.png) Subs

----------------------------------------------------------------------------------------------------------------------------------------------
Log: 
[MKVBatchMultiplex.log](https://github.com/akai10tsuki/mkvbatchmultiplex/files/5027280/MKVBatchMultiplex.log)

**Comment by akai10tsuki** [comment]
Good day,

Output Directory - Y:\Anime2\Boruto - Naruto Next Generations\Episodes 001-016 (The Ghost Incident)

Y:\Anime2\Boruto - Naruto Next Generations\Episodes 001-016 (The Ghost Incident)\Boruto - s01e01 - AnimeRG - Uzumaki Boruto!! (1).mkv

Source Directory 1 - Y:\Anime2\Boruto - Naruto Next Generations\Episodes 001-016 (The Ghost Incident)

( Y:\Anime2\Boruto - Naruto Next Generations\Episodes 001-016 (The Ghost Incident)\Boruto - s01e01 - AnimeRG - Uzumaki Boruto!!.mkv )

Source Directory 2 - Z:\Anime Backups\Boruto\Erai-raws\Italian_1-77

( Z:\Anime Backups\Boruto\Erai-raws\Italian_1-77\[Erai-raws] Boruto - Naruto Next Generations - 01 [720p][Multiple Subtitle]_track8_ita.ass )

The directories in use show a possible problem I am assuming 1-77 means 77 episodes.  The program is non destructive it won't override destination or delete any source this means you need the drive space to hold the new multiplexed files.  The output directory is the same directory as the source directory 1 in order to run there should be exactly 77 *.mkv files there I am reading the directories the name of the files has no meaning in matching the files to multiplex the order of the files do.  **Source 2** is perfectly ok. Recommend to **change the destination or output directory**.  And only leave the real source files in **Source 1**. Usually when there are so many files you will have to run the program more than once because as noted before the structure the order of the tracks has to be the same.  I find that to be true for a group of files the way do this is for example:

episodes 1 - 50

Tracks

video
audio
sub jpn
sub eng

episodes 51 - 77

Tracks

video
audio
sub eng
sub jpn

When run using episode 1 as the base on it should run for the first 50 episodes right now the program just substitutes destination and source files so it will fail from 51 on wards.

Take now episode 51 as base and do the same operations with mkvtoolnix-gui and run the program again with the same source and destination directories it should fail for episode 1-50 but work with 51-77.

Other option than I have to do when the episodes are pretty inconsistent I see you have a source directory for subs assuming you de-multiplex them if you have the space is to de-multiplex the episodes and every source video, audio and subs in it's own directory as the destination also in a different directory de-multiplex program also run in batch mode.

Right now change the destination directory and be sure to only have the corresponding episodes to the subs you need if the source mkv are consistent it should run ok.

If this work I will work with you in order to make it work but this is a mayor change in the paradigm of the program so it may take a little time. Changing the destination directory may do the trick.

The link for the version v2.0.0a2dev1 will show you the directories scanned with the files and any differences in the total of files expected.

https://github.com/akai10tsuki/mkvbatchmultiplex/releases/download/v2.0.0a1/MKVBatchMultiplex-iss-AMD64-2.0.0a2dev1.exe

**Comment by zFerry98** [comment]
Okay, I'm using the new version. I changed the save path but still gives the same error: 
![image](https://user-images.githubusercontent.com/17975351/89527286-5f090580-d7e9-11ea-8469-01a2d6227e04.png).

`C:\Users\MSI\Downloads\EXE\mkvtoolnix\mkvmerge.exe --ui-language it --output ^"Y:\Anime2\Boruto - Naruto Next Generations\batch\Boruto - s01e01 - AnimeRG - Uzumaki Boruto^!^!.mkv^" --language 0:jpn --track-name ^"0:[AnimeRG]^" --default-track 0:yes --display-dimensions 0:1920x1080 --language 1:jpn --track-name ^"1:Japanese Stereo^" --default-track 1:yes --sub-charset 2:UTF-8 --language 2:eng --track-name ^"2:Crunchyroll Eng^" --sub-charset 3:UTF-8 --language 3:ita --track-name ^"3:Crunchyroll Ita SRT^" ^"^(^" ^"Y:\Anime2\Boruto - Naruto Next Generations\Episodes 001-016 ^(The Ghost Incident^)\Boruto - s01e01 - AnimeRG - Uzumaki Boruto^!^!.mkv^" ^"^)^" --language 0:ita --track-name ^"0:Crunchyroll Ita^" --default-track 0:yes --sync 0:26 ^"^(^" ^"Z:\Anime Backups\Boruto\Erai-raws\Italian_1-77\[Erai-raws] Boruto - Naruto Next Generations - 01 [720p][Multiple Subtitle]_track8_ita.ass^" ^"^)^" --track-order 0:0,0:1,0:2,1:0,0:3`

### While if I leave only 16 ass it works:
![image](https://user-images.githubusercontent.com/17975351/89527780-2ddd0500-d7ea-11ea-846c-15803b06cda5.png)

`C:\Users\MSI\Downloads\EXE\mkvtoolnix\mkvmerge.exe --ui-language it --output ^"Y:\Anime2\Boruto - Naruto Next Generations\batch\Boruto - s01e01 - AnimeRG - Uzumaki Boruto^!^!.mkv^" --language 0:jpn --track-name ^"0:[AnimeRG]^" --default-track 0:yes --display-dimensions 0:1920x1080 --language 1:jpn --track-name ^"1:Japanese Stereo^" --default-track 1:yes --sub-charset 2:UTF-8 --language 2:eng --track-name ^"2:Crunchyroll Eng^" --sub-charset 3:UTF-8 --language 3:ita --track-name ^"3:Crunchyroll Ita SRT^" ^"^(^" ^"Y:\Anime2\Boruto - Naruto Next Generations\Episodes 001-016 ^(The Ghost Incident^)\Boruto - s01e01 - AnimeRG - Uzumaki Boruto^!^!.mkv^" ^"^)^" --language 0:ita --track-name ^"0:Crunchyroll Ita^" --default-track 0:yes ^"^(^" ^"Z:\Anime Backups\Boruto\Erai-raws\IT-Sedici\[Erai-raws] Boruto - Naruto Next Generations - 01_ita.ass^" ^"^)^" --track-order 0:0,0:1,0:2,1:0,0:3`

----------------------------------------------------------------------------------------------------------------------------------------------

So I have to either put all the video sources together or even divide the subs by folders (in doing so, however, I should copy the shell for each saga).

Now I try to do other batches and see.
Thanks for the support 👍

**Comment by akai10tsuki** [comment]
Hi,

Checking the documentation I realize that I haven't explaining myself quite clear. I have been working with this for years.

Let follow an example:

I want to add Spanish subtitle a make it the default.

Directories:

-  E:\Anime\Boruto\Video - source episodes
-  E:\Anime\Boruto\Subs - subtitles
-  E:\Anime\Boruto\Output - multiplexed video

The directories can be in different drives without problem.

This is the original file or base file.

![image](https://user-images.githubusercontent.com/37753164/89545143-fb72de00-d7d0-11ea-99e1-9ab631f93a2a.png)

The operation on the base file that I want.

![image](https://user-images.githubusercontent.com/37753164/89545400-4bea3b80-d7d1-11ea-9d9c-9c16751f3790.png)

When checking command.

![image](https://user-images.githubusercontent.com/37753164/89545806-d03cbe80-d7d1-11ea-9d40-2f7f97d259f7.png)

Here I see that the source files total don't match.

Use **Check Files** we see:

![image](https://user-images.githubusercontent.com/37753164/89546574-be0f5000-d7d2-11ea-895e-1368a1fcae81.png)

- 1 option Check Files
- 2 commands cannot be generated
- 3 Destination directory 117 files

Scrolling down.

![image](https://user-images.githubusercontent.com/37753164/89547229-7f2dca00-d7d3-11ea-88b1-9e1b0f772a6a.png)

Source directory read 117 files this will always match the destination the destination is usually empty and all name collisions will be solved with a prefix newx new1-episode 01.mkv fist collision after 10 runs will be new10-episode 01.mkv.

Scrolling further down.

![image](https://user-images.githubusercontent.com/37753164/89548044-886b6680-d7d4-11ea-93e5-bfcecc0d8e1a.png)

- 1 Now we see a flag there are 118 subs 118 not 117. One sub to many or missing episode
- 2 After looking in the source directory there is one missing episode just luck we can see it here.

The program will flag the Subs directory because it takes the total number of files to check the other directories.

Restore missing episode 115 (program is caching info even with an error for now resubmit command so the commands are generated)

This is the end of the  run.

![image](https://user-images.githubusercontent.com/37753164/89548619-4131a580-d7d5-11ea-8621-390c20f5cad0.png)

As shown here it was a run on 118 episodes runtime 17 min 22 secs.

[fullrun.txt](https://github.com/akai10tsuki/mkvbatchmultiplex/files/5035783/fullrun.txt)

After every run always look on **Jobs Errors** tab.

![image](https://user-images.githubusercontent.com/37753164/89549225-0ed47800-d7d6-11ea-9d05-326af6102a0d.png)

As seen here there were no errors.  This is a controlled run by me but it really is normal of what I experience.  The job ID is auto generated 573 means that in testing and real runs I used the program that many times.  I hope you still have the original case and if you have time follow this and post results. Also remember you can make suggestions with case studies to see if I can program it for any case I have not seen.

Good day.

**Comment by zFerry98** [comment]
Ok. 2 things then:
1) In the guide I did not understand how it behaves with attachments. For example, the subs erai-raws have no attachments, however those of another language are there.
1 | are they copied?
2 | if they are copied, assuming that episode 22 has 5 more attachments and the remaining episodes are identical to the previous ones ... will the 5 more attachments be added?
2) If there is a title in the output (e.g., the episode title, which obviously each episode is different) he will copy that identical title on the whole batch ... Mkvtoolnix allows you to automatically choose whether to copy the title from the last file added or keep that of the first file added. What I wanted is to be able to choose as on mkvtoolnix which setting to use and consequently a similar result:

1) Source: Bofuri ep 1 jap.mkv (title: empty)
2) Source2: Bofuri ep1 eng mapleclub.mkv (title: <Defensive build and first battle>)

When the program opens the command on mkvtoolnix he will automatically (from the flag set in the settings) add the title or the last file added to the tail of the final mkv or keep the first title. I repeat, it is not a title that I put (obviously that cannot understand how to put it) but it is the title already included in the mkv.

**Comment by akai10tsuki** [comment]
Here you found another bug for the episode titles. The title is wrongly propagating the title in the command line another version with the fix will be attached.

Since the when mkvtoolnix-gui finds a title this is set on the command.  Version 1.0 removed this instruction but version 2.0 is preparing to get the title from other source (thetvdb.com for example).  Also considering using the OS name for the names like Series Title - S01E01 - Episode Title.mkv.  For the later will be easier by extending the Rename tab.


Attachment and chapters when not specified as external files will be copied. 

Attachments are the same for every episode if there are 2 external attachments those 2 will be multiplexed to every file.

Titles will be set explicitly if one is found on the base file which the program should not propagate when functioning correctly.

For Chapters if the same as for other files if external there have to be one for every episode.

This version should work OK with the episode titles.

https://github.com/akai10tsuki/mkvbatchmultiplex/releases/download/v2.0.0a1/MKVBatchMultiplex-iss-AMD64-2.0.0a2dev3.exe

I am preparing a public beta with the code as it is now.  Then will work with files with the same structure but out of order I think this feature if the program is started to be used by Anime fans it will be more helpful.  It will take time I have done some analysis I since I don't really need it I always goes back to the bottom of the list.

**Comment by zFerry98** [comment]
OK thanks. I'm about to make a batch of Kaguya (hoping that the subtitles are all the same time otherwise I have to do it by hand) and I tell you with the titles how it behaves ... maybe it's because I wrote wrong or then I can't understand well, the issue of attachments is like this:
Source Episodes - 20/20 (no attachment)
Episodes to add - 1/14 (same number of attachments)
Episode 15 has a karaoke and therefore 6 more attachments than the usual ones included from 1-14 ... those 6 more attachments are added as it is right that it is only at ep 15 or are they not really added?
By default mkvtoolnix adds all attachments included in the added mkv to the queue. Or does the program take ep 1 as a basis that NOT having the 6 attachments more than ep 15 then ep 15 will have the same attachments as ep1?

That was what I didn't understand. Because it can happen like in BOFURI that some episodes have lyric songs and therefore some fansubs add karaoke in the subs = that specific episode will have more attachments than ep 1 used as the basis for the command. Mainly I just want to understand.

**Comment by zFerry98** [comment]
OK, lol... If I open an MKS with audio flac and subs in ass ... if I try to export the MKS only with the SUBS without the flac it tells me wrong command.
`C:\Users\MSI\Downloads\EXE\mkvtoolnix\mkvmerge.exe --ui-language it --output ^"G:\Backup Anime\Dragon Ball Super\DBF DBS BD MKA\Exp\DBF_Dragon_Ball_Super_13_BDRIP_10bit.mks^" --no-audio --sub-charset 0:UTF-8 --language 0:ita --track-name ^"0:Dragon Ball Forever^" --default-track 0:yes ^"^(^" ^"G:\Backup Anime\Dragon Ball Super\DBF DBS BD MKA\DBF_Dragon_Ball_Super_13_BDRIP_10bit.mka^" ^"^)^" --title ^"^"`

![image](https://user-images.githubusercontent.com/17975351/89710621-00788e80-d985-11ea-83d1-1d73fba5fba3.png)

Log: 
[MKVBatchMultiplex.log](https://github.com/akai10tsuki/mkvbatchmultiplex/files/5045251/MKVBatchMultiplex.log)

![image](https://user-images.githubusercontent.com/17975351/89710625-0a9a8d00-d985-11ea-92f0-4f237227c215.png)

**Comment by moralia** [comment]
I have had the same problem. What I wanted to do is add an audio only, regardless of what was in the source video. Some chapters 1 audio and 2 subs and other 2 audios and 3 subs. I've been around a lot but it won't let me do it with this program. Which by the way, is very good for many other things in batches.

My recomendation:
Extract audios with MKVCleaver.
Everything in the same folder:
Video: Legend 1x01.mkv
Audio: Legend 1x01_track02.mp3
.......
Create a .bat in the same folder as videos and audios or subtitles to join.

for %% A IN (* .mkv) do (
"C: \ Program Files \ MKVToolNix \ mkvmerge.exe" -o "remux - %% ~ nxA" "%% ~ A" "%% ~ nA_Track02.mp3"

)
PAUSE

Run and go. Now you just have to modify the header to make it your own.

**Comment by akai10tsuki** [comment]
About attachments.

When the attachments are in the the source files they are copied. mkvmerge behaves that way with the attachments it will merge them also.  Unless the attachments are modified in any way remove some or all of them then there will be specific instructions in the command that will propagate to all episodes the same way.

No attachments on the base episodes and variable attachments on the source episodes for the subs results in all attachments copied to the resulting video file.

Example 1:

**Base episode 1** no attachments, Source for subs 1  **4 attachments** the subtitle only uses 3 of the attachments 

**Result episode 1** will have **4 attachments**.  All the attachments are copied the sub with karaoke will find the correct fonts attached to the file.  The attachment if there are any they are just copied mkvmerge does not now how they are used.

Example 2:

Base episode 2 1 attachment, Source for subs 2 7 attachments

Result episode 2 will have 8 attachments unless attachment for episode 2 is included in 7 of the subs file.

The problem you could encounter is the structure of the files for now it has to be the same.  Same number of tracks, same type,
same order.  This is my next step to relax this.

There is another version of the program for the titles as posted earlier:

https://github.com/akai10tsuki/mkvbatchmultiplex/releases/download/v2.0.0a1/MKVBatchMultiplex-iss-AMD64-2.0.0a2dev3.exe


**Why is not doing this:**

Moritz Bunkus about MKVToolnix GUI doing a batch process

https://gitlab.com/mbunkus/mkvtoolnix/-/wikis/Batch-muxing-with-the-GUI

**"Sorry, but such a feature will never be implemented in MKVToolNix GUI itself."**

Also I have only work with **video files**.

`C:\Users\MSI\Downloads\EXE\mkvtoolnix\mkvmerge.exe --ui-language it --output ^"G:\Backup Anime\Dragon Ball Super\DBF DBS BD MKA\Exp\DBF_Dragon_Ball_Super_13_BDRIP_10bit.mks^" --no-audio --sub-charset 0:UTF-8 --language 0:ita --track-name ^"0:Dragon Ball Forever^" --default-track 0:yes ^"^(^" ^"G:\Backup Anime\Dragon Ball Super\DBF DBS BD MKA\DBF_Dragon_Ball_Super_13_BDRIP_10bit.mka^" ^"^)^" --title ^"^"`

In this command in particular the program will flag --track-order missing.

The internals of the program are like this:

The command:

'C:/Program Files/MKVToolNix/mkvmerge.exe' --ui-language en --output 'E:\Example\Series Title (2017)\Season 01\Episode - S01E03 (1).mkv' --language 0:und --default-track 0:yes --display-dimensions 0:1280x720 --language 1:jpn --default-track 1:yes --sub-charset 2:UTF-8 --language 2:eng '(' 'E:\Example\Series Title (2017)\Season 01\Episode - S01E03.mkv' ')' --no-audio --no-video --sub-charset 2:UTF-8 --language 2:ita --track-name 2:Italian --default-track 2:yes '(' 'E:\Example\Series Title (2017)\New Sub\Episode (Italian Subs) - S01E03.mkv' ')' --track-order 0:0,0:1,1:2,0:2

Will translate to this template.  The command is not altered in any way.

'C:/Program Files/MKVToolNix/mkvmerge.exe' --ui-language en --output <OUTPUTFILE> --language 0:und --default-track 0:yes --display-dimensions 0:1280x720 --language 1:jpn --default-track 1:yes --sub-charset 2:UTF-8 
--language 2:eng <SOURCE0> --no-audio --no-video --sub-charset 2:UTF-8 --language 2:ita --track-name 2:Italian --default-track 2:yes <SOURCE1> --title <TITLE> --track-order 0:0,0:1,1:2,0:2

Tokes <OUTPUTFILE>, <SOURCE0> <SOURCE1> <TITLE> are substituted in the command the command is not altered in any form. 

For this:
1. I first check the command to see if conforms to this form that's is why I work with a copy of the command generated in order to work with the same structure of the command.  Substitute the tokens in the command.
2. I read all the directories for the <SOURCE0> and <SOURCE1> tokens and analyze it structure.  Since the command is the same for all is espected that the sources be the same in structure again same number of tracks same type same order.
3. Generate how many commands as number of <SOURCE0> files are found.  Here is another restriction 20 files found in <SOURCE0> then <SOURCE1> needs to have 20 files.
4. If everything is OK the submit each command in order to a sub process 

The restrictions are because the results produced this way are reliable the program does not have to make any decisions about what to do.  And I maintain a rather large collection of series this way.

--track-order 0:0,0:1,1:2,0:2 this is the key to have variable number of tracks in the sources I have to identify and modify these id's
the structure of the command if basically unaltered still.

I hope that knowing a little about the internals will help with the expectations. The way I works right now is to ensure it runs in a consistent way with the least amount of inter version. In order to do more I need case studies like these

1. mkvtoolnix-gui command line.  The command has to have an identifiable pattern to get the sources and do  substitution.
2. What is needed what is expected to be the end result.
3. Description of the structure of the files number of tracks, type and order for more than one case.  Same number of tracks?
Same order? Unordered?.  As detail as possible so I can recreate the case to work on it.
4. Directories used list of the files described on 3

This with as much detail as possible. 

Food for though.  

Variable number of tracks and I want to add a subtitle for the one file to another I want track 6 from Source 1 sub in the command generated.

1. Source Sub:
 1. Video
 2. Audio jpn - Default
 3. Audio rus
 4. Sub rus - Default
 5. Sub eng - Songs/Signs
 6. Sub eng - Dialog

2. Source Sub:
 1. Audio jpn
 2. Video
 3. Audio rus - Default
 4. Sub eng - **No description**
 5. Sub rus
 6. Sub ita
 7. Sub eng - **No description**

This is typical case found on some group with multi-language subs.  I wan't the user wanted one English on the 2 in each file without been in the same order and no consistent track name.  This is a case where there is no way for program to  make a decision without human intervention.  Even after running an selecting the first English track without watching to see if the sub is for the Dialog or Songs/Signs. The batch process is less useful it goes back to doing every episode manually.  A case like this made me abandon the idea of working with variable structure.  For now what is in the agenda is variable order of the same type of tracks and when not the same amount of tracks the tracks must have only one type of the selected one.  If I select English sub there has to be only one English sub out of order.

If everything is de-multiplexed and every type of track is in its own directory I can work to multiplex by directory instead of individual files.  For example for attachments if the programs looks for the attachments in a directory that consist of sub directories corresponding to one for each base file it will attach whatever it finds in each directory.  It may be possible to extend that for other type of files.  Emphasis on **may**.

So propose enhancements and let's see way I can do about it.

For now think about this a special selectable mode:

I will not check any instruction for soundness and only look for 

--output <OUTPUTFILE>

and 

( <SOURCE0> ) .. ( <SOURCE1> )

make the substitutions and execute.

Still it has to match in the number of files 20 <SOURCE0> and 20 <SOURCE1>

There is nothing to expect about results this is more a just to see what happens.

**Comment by zFerry98** [comment]
😵😁 Sorry but I feel bad these days and I'm not doing anything. If I can I try to redo the batch today. The fact that this software exists is already a win (for me) I don't understand why not introduce it in the official GUI ...

**Comment by zFerry98** [comment]
I did a lot of batches and they all went well👍.
I'm talking about the "normal" ones.
@akai10tsuki
