### ISSUE TITLE
[BUG? / Feature] --track-order for MKS/A (MKV without Video or/and Audio) export a .mkv instead of an MKS / A

### ISSUE THREAD

**Issue by zFerry98** [akai10tsuki/mkvbatchmultiplex#6]
As the title suggests, I went into batching to export to MKA / S.
And apparently it works. Except that it exports to .MKV (thankfully MKV toolnix sees it anyway) I know that BulkRename would be enough to change .mkv to the right one.

@moralia
### The system to make the batch work (which I finally understood):
`C:\Users\MSI\Downloads\EXE\mkvtoolnix\mkvmerge.exe --ui-language it --output ^"G:\Backup Anime\[KonaWolf Fansub] Miru Tights - 01v2 [BD].mks^" --no-audio --no-video --sub-charset 2:UTF-8 --language 2:it --track-name 2:KonaWolf --default-track 2:yes ^"^(^" ^"C:\Users\MSI\Downloads\Telegram Desktop\[KonaWolf Fansub] Miru Tights [BD]\[KonaWolf Fansub] Miru Tights - 01v2 [BD].mkv^" ^"^)^" --title ^"^"`
is the original command from MKVToolNix GUI
![image](https://user-images.githubusercontent.com/17975351/93014976-b4d58800-f5b5-11ea-968a-70b485d76013.png)
Just add `--track-order 0:2` to the end of the command.
0:2 must be replaced with track order (in my case for MKVToolNix it is seen as 0: 2, obviously if you move the tracks, the values also change).

## Problem:
Export to .mkv

----------------------------------------------------------------------------------------------------------------------------------------------
Anyway thanks to this I can now batch 800 episodes to extract audio / subs only 👍😁👌😵🐱‍🏍

**Comment by akai10tsuki** [comment]
I only work with video files and those will have at least 2 tracks one video and one audio.  That is why I look for --track-order on the command and see it missing as an error.

This is a feature I will check now how to support the case of one track only and make sure the output extension does not change.  Right now I have no Idea of how much time I will need.

**Comment by zFerry98** [comment]
No problem. I didn't know if he wasn't using the right extension because of me or whatever.
The problem with adding the `--track-order x:x` is that it gets put if I change positions. On the other hand, if I simply check the audio and video track, he considers that of the current mkv as `--track-order`. By doing so, they have saved CLI users from having them write `--track-orders` and check the various orders for the tracks.
Finally I want to clarify that I wanted to use .bat to do this procedure but as I imagined, say: for each * .mkv execute this command ... and the command is a generic command to be used in CLI for mkvtoolnix messes with mkvs which have traces ordered differently from each other and not only that. So this program is truly a pearl 👍👌😁

**Comment by akai10tsuki** [comment]
Hi,

This is the first developer release of version 2.1.0.

https://github.com/akai10tsuki/mkvbatchmultiplex/releases/download/v2.1.0b1.dev1/MKVBatchMultiplex-2.1.0a1.dev1-iss-AMD64.exe

I was able to add support for one track files --track-order not needed when there is only one track.  Also the extension should be correct now mkv, mka or mks as in the command from mkvtoolnix-gui.  The new operating mode (Algorithms) should be set to 1 witch is the default.  Then if the track changes position it still will many be found and muxed:

The command was constructed with file one.mkv and I want the subtitle (mks)

one.mkv

track 1: video
track 2: audio
track 3: subtitle

two.mkv

track 1: video
track 2: audio
track 3: audio
track 4: subtitle

one.mks

track 1: subtitle

two.mks

track 1: subtitle

Algorithm 0 will fail files don't have the same structure file two.mkv has 2 audio tracks instead of one.  Algorithm 1 will see the difference in structure but it will look in the source for a subtitle track that best matches what was selected in the command.  The selection logic is not so straight forward for example if it was the audio track as you can see there are two in the second file there may be cases that the second audio track if the best choice.  I will explain it **latter** with examples in the wiki.

The program takes into consideration:

Track type
Track language
Track format (codec)
Track position
Track position within the type
Track position within the same language
Track title in the file

**Comment by zFerry98** [comment]
It works great. The introduction of algorithms is a big step forward.
I noticed how with 1 it can be handy for those files they have
mixed tracks instead of all in perfect order. Made 7 batches and they all went well👍.
