### ISSUE TITLE
[BUG] Deleted queues are still performed

### ISSUE THREAD

**Issue by zFerry98** [akai10tsuki/mkvbatchmultiplex#7]
![image](https://user-images.githubusercontent.com/17975351/94335509-455f8f80-ffdc-11ea-90e9-f7a1afcd0acc.png)
Jobs in this list even if they are deleted, when you start the worker they are executed. 

## How to reproduce error:
Add a Job, 
Go to the Job list and delete it, 
add another job, 
start the worker...
= The job you deleted starts.

I actually encountered this problem in previous versions as well.
Thanks in advance (as you can see I've done nearly 200 jobs by now😁)

**Comment by akai10tsuki** [comment]
Hi,

This is a fast workaround instead of deleting the job double click on the status of the job and changed the status to Skip.  Changing the status is the way I meant it to work with the jobs queue.  The "Remove" should not be there as you should have notice it doesn't even ask before removing which is a real an inconvenience.  If something is removed by mistake you have to recreate the command all over again.  That is why I decided to only use the status of the jobs,  "Skip" leaves the job on the list.  I will work on a fix for "Remove".

**Comment by akai10tsuki** [comment]
Hi,

This turns out to be it should be simple but..

https://github.com/akai10tsuki/mkvbatchmultiplex/releases/download/v2.1.0b1.dev1/MKVBatchMultiplex-2.1.0b1.dev2-iss-AMD64.exe

The complication is what to do when the worker is running.   Sometimes the item should not be removed for example if it is running is has to be stopped before removing.  This can be done using the drop down from the status field.  So there is quite a bit of logic that has to be worked out.
